---
- hosts: nodes
  become: yes
  tasks:
  - name: Wait for the auto-update Ubuntu does on first boot.
    shell: while sudo fuser /var/lib/dpkg/{{ item }} >/dev/null 2>&1 ; do sleep 1 ; done
    loop:
      - lock
      - lock-frontend
  - name: Wait for the auto-update Ubuntu does on first boot.
    shell: while sudo fuser /var/lib/apt/lists/{{ item }} >/dev/null 2>&1 ; do sleep 1 ; done
    loop:
      - lock
      - lock-frontend
  - name: apt-get update
    apt:
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
  - name: apt-get upgrade
    apt:
      upgrade: dist 
      force_apt_get: yes
  - name: install nfs-common (needed for csi mount)
    apt: pkg=nfs-common state=latest
  - name: Install Python3
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - python3
      - python3-pip
  - name: Check if the instance needs a reboot.
    stat: 
      path: /var/run/reboot-required
    register: f
  - name: Reboot if needed
    reboot:
    when: f.stat.exists

  